### ISSUE TITLE
Switch automatically to next octet

### ISSUE THREAD

**Issue by RobertPaulson90** [shlomiassaf/ngx-ip#2]
This component is great, but is it possible to:

1.  make it so that commas also bring you to the next field (EU keyboard numpad has a comma, not period)
2. Typing three numbers within an octet input, automatically bring you to the next octet

**Comment by shlomiassaf** [comment]
1 & 2 done in version 1.0.2 (make sure to install `ngx-ip` and not `ng2-ip`)

Also added lots of other features.

**Comment by RobertPaulson90** [comment]
You're the man! Great(er) UX. Thanks for that!
